### ISSUE TITLE
Reducing size of picture in each blog (suggestion)

### ISSUE THREAD

**Issue by pattarinn** [NarawishS/ku-hub#65]
In all blog page, if the image of the blog is too large (mostly a portrait picture), it will take some time to scroll down and see the blog's detail. It would be nice if you reduce the size of the image. Other functions are cool :DDDD

**Comment by NarawishS** [comment]
We made it so one page only contain 3 blog at most so the scroll should not be too long.

**Comment by keyboard2543** [comment]
@pattarinn: 
> In all blog page, if the image of the blog is too large (mostly a portrait picture), it will take some time to scroll down and see the blog's detail. It would be nice if you reduce the size of the image. Other functions are cool :DDDD

+1 with @NarawishS: 
> We made it so one page only contain 3 blog at most so the scroll should not be too long.

@pattarinn 
We are glad that you like our functions. 

And we saw that the some of uploaded portrait pictures are too long and take some time to scroll down to see the blog's detail.
Thanks, we will try to follow your suggestions.

**Comment by NarawishS** [comment]
we discuss that the new fix for the image is not good so we gonna use the old one
