### ISSUE TITLE
Blog with same name can be created

### ISSUE THREAD

**Issue by ttxking** [NarawishS/ku-hub#68]
I'm not sure whether if this allowed in your site, but a blog with the same name can be created, but when I try to find my blog on the home page, only one is shown.

When I conducted the search, two of them are shown on the search page, but if you allowed blog with the same name. You should you picture in order to avoid confusedness of the users.

**Comment by NarawishS** [comment]
@ttxking thank you for the suggestion, I think that blog should be able to name the same as others so we will not fix this but we will add an image to the blog like what you suggest.
