### ISSUE TITLE
Functionality: I found bad link on https://jix.herokuapp.com/events/ page

### ISSUE THREAD

**Issue by ZEZAY** [NarawishS/ku-hub#72]
I used selenium then found a bad link.
Url: https://jix.herokuapp.com/events/

![image](https://user-images.githubusercontent.com/44806732/100914031-1d713880-3505-11eb-82ff-77b3736b703b.png)

![image](https://user-images.githubusercontent.com/44806732/100914048-206c2900-3505-11eb-9818-b0b06d82a0d1.png)

**Comment by LevNut** [comment]
@ZEZAY Our website named "KU-HUB", so I think you might post the issues at wrong place. 

// Someone posting their link at the wrong place in project-testing sheet.
