### ISSUE TITLE
I found the Post form display as a user profile and send it!

### ISSUE THREAD

**Issue by ZEZAY** [NarawishS/ku-hub#73]
I found that the site uses Post form on the user profile page, so I use inspect to edit something.
And I see that I can send the edit of that profile, even though it gets rejected.

![image](https://user-images.githubusercontent.com/44806732/100915993-b99c3f00-3507-11eb-98c3-6bb57430799f.png)

**Comment by LevNut** [comment]
@ZEZAY Our website named "KU-HUB", so I think you might post the issues at wrong place. 

// Someone posting their link at the wrong place in project-testing sheet.

**Comment by Kuea666** [comment]
;-; เเล้วงัย

**Comment by Kuea666** [comment]
;-;
