### ISSUE TITLE
Other: It look like the server will alway return Error (500) for user who enter javascript as his name

### ISSUE THREAD

**Issue by ZEZAY** [NarawishS/ku-hub#74]
I try to enter my username with javascript, and then every single page (when I still log in), returns Server Error (500).
It works normally when I didn't login thoungh.

URL: https://jix.herokuapp.com/

![image](https://user-images.githubusercontent.com/44806732/100939622-2e33a580-3529-11eb-97d6-de1222f4e73c.png)

**Comment by LevNut** [comment]
@ZEZAY Our website named "KU-HUB", so I think you might post the issues at wrong place. 

// Someone posting their link at the wrong place in project-testing sheet.
