### ISSUE TITLE
Javascript successfully display alert box.

### ISSUE THREAD

**Issue by Sahadporn** [NarawishS/ku-hub#78]
url:https://kuhub.herokuapp.com/blog/8/

I tried input pop up alert javascript instead of blog information.

1. Click add blog, Then type <script>alert('test alert')</script> into the short description.
![kuhub2](https://user-images.githubusercontent.com/59825486/101126130-6a502e80-362d-11eb-865a-152c94a0b5ac.png)

2. The Javascript successfully pop up when I click 'Blog Entry'.
![kuhub1](https://user-images.githubusercontent.com/59825486/101126143-70dea600-362d-11eb-95c7-fe558f76c90d.png)

**Comment by NarawishS** [comment]
@Sahadporn Thankyou for the information we will fix it ASAP
