### ISSUE TITLE
Html working on some page.

### ISSUE THREAD

**Issue by ZEZAY** [NarawishS/ku-hub#79]
I use some HTML&JS at the 'Short description' of the blog. 
It works only on the homepage, on its blog page, it doesn't work.

URL homepage: https://kuhub.herokuapp.com/
URL blog: https://kuhub.herokuapp.com/blog/11/

![image](https://user-images.githubusercontent.com/44806732/101129291-e483b180-3633-11eb-8a73-f54aa2b72891.png)
![image](https://user-images.githubusercontent.com/44806732/101129302-e8afcf00-3633-11eb-948e-b166fb64c598.png)

**Comment by NarawishS** [comment]
@ZEZAY Thankyou for the information we will fix it ASAP
