### ISSUE TITLE
When trying to view other profile without login, the site return Server Error (500)

### ISSUE THREAD

**Issue by ZEZAY** [NarawishS/ku-hub#80]
I trying to view the blog owner profile when I didn't log in, the site return Server Error (500).
It works only when I log in though.

URL: https://kuhub.herokuapp.com/accounts/10/profile/

before log in:
![image](https://user-images.githubusercontent.com/44806732/101129726-b9e62880-3634-11eb-84cf-8b7d11de6e84.png)
![image](https://user-images.githubusercontent.com/44806732/101129794-de420500-3634-11eb-8a31-81ee9c2680ed.png)

after log in:
![image](https://user-images.githubusercontent.com/44806732/101129750-c79bae00-3634-11eb-9a76-fcdbf4fa0e7b.png)

**Comment by NarawishS** [comment]
@ZEZAY Thankyou for the information we will fix it ASAP
