### ISSUE TITLE
Cannot login to KUHub

### ISSUE THREAD

**Issue by james31366** [NarawishS/ku-hub#81]
When I need to signup KUHub with google oAuth it's getting an error. Also, this web can log in only google oAuth cannot log in with other services.

At Login: http://kuhub.herokuapp.com/accounts/login/

Error URL: https://accounts.google.com/signin/oauth/error?authError=ChVyZWRpcmVjdF91cmlfbWlzbWF0Y2gSuAJUaGUgcmVkaXJlY3QgVVJJIGluIHRoZSByZXF1ZXN0LCBodHRwOi8va3VodWIuaGVyb2t1YXBwLmNvbS9hY2NvdW50cy9nb29nbGUvbG9naW4vY2FsbGJhY2svLCBkb2VzIG5vdCBtYXRjaCB0aGUgb25lcyBhdXRob3JpemVkIGZvciB0aGUgT0F1dGggY2xpZW50LiBUbyB1cGRhdGUgdGhlIGF1dGhvcml6ZWQgcmVkaXJlY3QgVVJJcywgdmlzaXQ6IGh0dHBzOi8vY29uc29sZS5kZXZlbG9wZXJzLmdvb2dsZS5jb20vYXBpcy9jcmVkZW50aWFscy9vYXV0aGNsaWVudC8ke3lvdXJfY2xpZW50X2lkfT9wcm9qZWN0PSR7eW91cl9wcm9qZWN0X251bWJlcn0aRWh0dHA6Ly9kZXZlbG9wZXJzLmdvb2dsZS5jb20vYWNjb3VudHMvZG9jcy9PQXV0aDJMb2dpbiNzZXRyZWRpcmVjdHVyaSCQAw%3D%3D&client_id=866699505628-khia9umnev7u8ihqf7mdt12g76v40k6u.apps.googleusercontent.com

![image](https://user-images.githubusercontent.com/5600277/101146900-333e4500-364e-11eb-97cf-507e19f5cf41.png)

**Comment by NarawishS** [comment]
@james31366 thank for the feed back
for the error I try it and I don't see any error that you tell us we need more information for this because there are problem with google Oauth at the moment. sorry for the inconvenient
and about how to signup process it is our feature that you need to signin or signup with KU mail only.

**Comment by NarawishS** [comment]
@james31366 I research a little and have found that it is a problem with the oauth 2

**Comment by NarawishS** [comment]
I have found the problem it seems that my callback URL is correct but there need to have 2 URL that is HTTP and HTTPS, I have fixed it already if the problem arises again feel free to tell us.
