### ISSUE TITLE
can use JavaScript in blog's body

### ISSUE THREAD

**Issue by KongtappV** [NarawishS/ku-hub#82]
when you add source in the blog edit page and enter JavaScript in the body part after you saved it when you redirect to Blog page javascript will run. In my case, I enter the alert in the source.

![image](https://user-images.githubusercontent.com/59852173/101154552-76051a80-3658-11eb-8906-45085ee210e7.png)

**Comment by NarawishS** [comment]
@KongtappV thankyou for the information, actually it is a feature of CKeditor but i do agree that it is a problem, we will remove the sorce function so this will not cause a problem for us in the future
