### ISSUE TITLE
Footer should fit the resolution and stay at the bottom

### ISSUE THREAD

**Issue by Sahanon-P** [NarawishS/ku-hub#83]
## I think the footer should be in the bottom of the screen
- As you can see this is your normal screen and it's work great!
![image](https://user-images.githubusercontent.com/59828276/101177235-28010e80-367a-11eb-8ec2-6cd51dc67edc.png)

- But in the forum page and also in the blog page the footer is not in the proper place. It should be on the bottom of the page.
![image](https://user-images.githubusercontent.com/59828276/101177299-3b13de80-367a-11eb-8c10-360229d34663.png)

It would be great if you guys can fix it. Your webpage will look better for sure XD.

**Comment by NarawishS** [comment]
@Sahanon-P thankyou for the suggestion, we will try to make it stay at the bottom without hindering other part of the blog
